services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: tabacomyu-app
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
      WS_PORT: ${WS_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    expose:
      - "${APP_PORT}"
    networks:
      - tabacomyu-net
    restart: unless-stopped

networks:
  tabacomyu-net:
    external: true
